// Generated from src/database/*.json by scripts/build-demo.mjs. Do not edit.
export default {
 "phrasesEn": [
  "dive into",
  "dive deep",
  "deep dive",
  "delve",
  "delve into",
  "crucial",
  "landscape",
  "robust",
  "leverage",
  "game-changer",
  "game-changing",
  "cutting-edge",
  "state-of-the-art",
  "revolutionize",
  "revolutionary",
  "transformative",
  "unprecedented",
  "unparalleled",
  "seamless",
  "seamlessly",
  "comprehensive",
  "holistic",
  "noteworthy",
  "remarkable",
  "exceptional",
  "innovative",
  "versatile",
  "foster",
  "streamline",
  "optimize",
  "enhance",
  "harness",
  "unlock",
  "curate",
  "curated",
  "tailored",
  "bespoke",
  "empower",
  "empowering",
  "synergy",
  "paradigm shift",
  "paradigm",
  "ecosystem",
  "unpack",
  "utilize",
  "journey",
  "tapestry",
  "mosaic",
  "masterfully",
  "moreover",
  "furthermore",
  "in addition",
  "additionally",
  "it is worth noting",
  "it's worth noting",
  "interestingly",
  "indeed",
  "essentially",
  "fundamentally",
  "in other words",
  "that said",
  "it is important to note",
  "it's important to note",
  "needless to say",
  "in today's world",
  "in today's fast-paced",
  "as we navigate",
  "in conclusion",
  "to summarize",
  "ultimately",
  "last but not least",
  "world-class",
  "firstly",
  "secondly",
  "thirdly",
  "in this regard",
  "to that end",
  "with that being said",
  "it could be argued",
  "one might say",
  "arguably",
  "realm",
  "endeavor",
  "multifaceted",
  "spearhead",
  "bolster",
  "let's unpack",
  "at the end of the day",
  "moving forward",
  "circle back",
  "double down",
  "pivot",
  "disrupt",
  "disruption",
  "disruptive",
  "next-level",
  "best-in-class",
  "value-add",
  "low-hanging fruit",
  "move the needle",
  "north star",
  "bleeding edge",
  "future-proof",
  "scalable",
  "actionable",
  "impactful",
  "thought leadership",
  "stakeholder",
  "bandwidth",
  "drill down",
  "level up",
  "take it to the next level",
  "on the same page",
  "reach out",
  "touch base",
  "loop in",
  "take offline",
  "at the forefront",
  "pave the way",
  "shed light on",
  "stand out from the crowd",
  "rest assured",
  "without further ado",
  "it goes without saying",
  "when it comes to",
  "in light of",
  "by the same token",
  "all things considered",
  "the bottom line",
  "at its core",
  "resonate",
  "elevate",
  "amplify",
  "catalyze",
  "orchestrate",
  "reimagine",
  "democratize",
  "operationalize",
  "incentivize",
  "contextualize",
  "strategize",
  "maximize",
  "minimize",
  "prioritize",
  "let me break this down",
  "let me explain",
  "let me walk you through",
  "here's the thing",
  "here's what you need to know",
  "here's the deal",
  "that being said",
  "having said that",
  "with that in mind",
  "it bears mentioning",
  "it should be noted",
  "on a broader scale",
  "in the grand scheme",
  "the crux of the matter",
  "by and large",
  "for all intents and purposes",
  "in a nutshell",
  "to put it simply",
  "in essence",
  "at the heart of",
  "in the realm of",
  "navigate the complexities",
  "navigate the landscape",
  "ever-evolving",
  "ever-changing",
  "fast-paced",
  "rapidly evolving",
  "dynamic landscape",
  "shifting landscape",
  "nuanced",
  "nuanced approach",
  "myriad",
  "myriad of",
  "plethora",
  "a plethora of",
  "a myriad of",
  "overarching",
  "underscore",
  "pivotal",
  "paramount",
  "indispensable",
  "imperative",
  "groundbreaking",
  "trailblazing",
  "pioneering",
  "thought-provoking",
  "insightful",
  "profound",
  "meticulous",
  "meticulously",
  "intricate",
  "intricacies",
  "akin to",
  "serves as a testament",
  "stands as a testament",
  "a testament to",
  "while it's true that",
  "on the flip side",
  "it's no secret that",
  "the elephant in the room",
  "food for thought",
  "the takeaway",
  "key takeaway",
  "wrapping up",
  "to wrap up",
  "in summary",
  "to sum up",
  "all in all",
  "above and beyond",
  "best practices",
  "pain point",
  "value proposition",
  "end-to-end",
  "full-stack",
  "soup to nuts",
  "from the ground up",
  "out of the box",
  "turnkey",
  "plug and play",
  "one-stop shop",
  "win-win",
  "synergize",
  "ideate",
  "iterate",
  "iterate on",
  "deep-seated",
  "robust framework",
  "robust solution",
  "holistic approach",
  "comprehensive guide",
  "definitive guide",
  "ultimate guide",
  "step-by-step guide",
  "hands-on",
  "real-world",
  "mission-critical",
  "great question",
  "excellent question",
  "what a great question",
  "i hope this helps",
  "hope this helps",
  "i hope this email finds you well",
  "hope this finds you well",
  "feel free to reach out",
  "don't hesitate to reach out",
  "let me know if you have any questions",
  "i'd be happy to help",
  "happy to help",
  "as an ai language model",
  "as an ai",
  "as of my last knowledge update",
  "i apologize for any confusion",
  "i apologize for the confusion",
  "you're absolutely right",
  "you are absolutely right",
  "in today's digital age",
  "in the digital age",
  "in today's digital landscape",
  "in the modern era",
  "in an era of",
  "in an increasingly",
  "in a world where",
  "now more than ever",
  "look no further",
  "whether you're a",
  "imagine a world",
  "picture this",
  "have you ever wondered",
  "let's dive in",
  "let's dive into",
  "let's delve",
  "let's explore",
  "let's take a closer look",
  "let's break it down",
  "let's break this down",
  "buckle up",
  "delving",
  "delved",
  "delves into",
  "delving into",
  "leveraging",
  "leveraged",
  "fostering",
  "harnessing",
  "harnesses",
  "unlocking",
  "empowered",
  "streamlined",
  "streamlining",
  "showcasing",
  "showcases",
  "underscoring",
  "underscored",
  "elevating",
  "navigating the complexities",
  "navigating the landscape",
  "revolutionizing",
  "spearheading",
  "spearheaded",
  "bolstering",
  "bolstered",
  "resonating",
  "reimagining",
  "reimagined",
  "utilizing",
  "embark on",
  "embarking on",
  "embark on a journey",
  "rich tapestry",
  "vibrant tapestry",
  "intricate tapestry",
  "rich cultural heritage",
  "nestled",
  "nestled in",
  "vibrant",
  "bustling",
  "breathtaking",
  "boasts",
  "a beacon of",
  "stands as a beacon",
  "enduring legacy",
  "lasting legacy",
  "indelible mark",
  "left an indelible mark",
  "deeply rooted",
  "plays a crucial role",
  "plays a pivotal role",
  "plays a vital role",
  "play a crucial role",
  "play a pivotal role",
  "play a vital role",
  "a pivotal role",
  "a crucial role",
  "a vital role",
  "highlighting the importance",
  "highlights the importance",
  "underscores the importance",
  "underscoring the importance",
  "pivotal moment",
  "a significant milestone",
  "key milestone",
  "it's important to remember",
  "it is important to remember",
  "it's important to understand",
  "it is important to understand",
  "it's crucial to",
  "it is crucial to",
  "it's essential to",
  "it is essential to",
  "it's worth mentioning",
  "it is worth mentioning",
  "worth noting",
  "unlock the power",
  "unlock the potential",
  "unlock the full potential",
  "unleash",
  "unleash the power",
  "harness the power",
  "harness the potential",
  "supercharge",
  "turbocharge",
  "skyrocket",
  "game changer",
  "stay ahead of the curve",
  "ahead of the curve",
  "to the next level",
  "next-gen",
  "next-generation",
  "seamless integration",
  "seamlessly integrate",
  "endless possibilities",
  "the possibilities are endless",
  "a world of possibilities",
  "revolutionize the way",
  "transform the way",
  "drive innovation",
  "driving innovation",
  "actionable insights",
  "valuable insights",
  "a deep understanding",
  "gain a deeper understanding",
  "commitment to excellence",
  "tailored to your needs",
  "user-centric",
  "frictionless",
  "future-ready",
  "best-of-breed",
  "generally speaking",
  "it's safe to say",
  "it is safe to say",
  "it's fair to say",
  "the fact of the matter",
  "make no mistake",
  "let's be honest",
  "let's face it",
  "truth be told",
  "here's why",
  "here's the kicker",
  "here's the catch",
  "to put it another way",
  "in closing",
  "final thoughts",
  "closing thoughts",
  "to conclude",
  "only time will tell",
  "the future is bright",
  "remains to be seen",
  "the road ahead",
  "paving the way",
  "let that sink in",
  "read that again",
  "no fluff",
  "zero fluff",
  "the real magic",
  "this is where it gets interesting",
  "here's where it gets interesting",
  "the uncomfortable truth",
  "the hard truth",
  "mind-blowing",
  "i'm thrilled to announce",
  "thrilled to share",
  "humbled and honored",
  "load-bearing",
  "doing the heavy lifting",
  "lean into",
  "leaning into",
  "double-edged sword",
  "the sweet spot",
  "unsung hero",
  "unsung heroes",
  "secret sauce",
  "ever-evolving landscape",
  "evolving landscape"
 ],
 "phrasesDe": [
  "revolutionaer",
  "bahnbrechend",
  "wegweisend",
  "transformativ",
  "beispiellos",
  "unvergleichlich",
  "erstklassig",
  "hochmodern",
  "nahtlos",
  "robust",
  "ganzheitlich",
  "umfassend",
  "tiefgreifend",
  "bemerkenswert",
  "aussergewoehnlich",
  "vielfaeltig",
  "innovativ",
  "massgeschneidert",
  "darueber hinaus",
  "des weiteren",
  "zusaetzlich",
  "in diesem zusammenhang",
  "es ist erwaehnenswert",
  "interessanterweise",
  "tatsaechlich",
  "im wesentlichen",
  "grundsaetzlich",
  "nichtsdestotrotz",
  "hinsichtlich",
  "diesbezueglich",
  "in anbetracht",
  "unter beruecksichtigung",
  "zusammenfassend",
  "abschliessend",
  "im grossen und ganzen",
  "letzten endes",
  "nicht zuletzt",
  "in der heutigen zeit",
  "in einer sich staendig veraendernden welt",
  "es sei darauf hingewiesen",
  "hervorzuheben ist",
  "anzumerken ist",
  "es laesst sich festhalten",
  "festzuhalten ist",
  "zweifellos",
  "zweifelsfrei",
  "unbestreitbar",
  "richtungsweisend",
  "zukunftsweisend",
  "zukunftsorientiert",
  "vielschichtig",
  "facettenreich",
  "paradigmenwechsel",
  "synergie",
  "synergieeffekte",
  "mehrwert",
  "wertschoepfung",
  "potenzial entfalten",
  "potenziale heben",
  "stellenwert",
  "tragweite",
  "implikationen",
  "dimension",
  "dynamik",
  "komplexitaet",
  "herausforderungen meistern",
  "chancen nutzen",
  "weichen stellen",
  "impulse setzen",
  "akzente setzen",
  "massstaebe setzen",
  "im fokus stehen",
  "im mittelpunkt stehen",
  "eine schluesselfunktion einnehmen",
  "eine zentrale rolle spielen",
  "von entscheidender bedeutung",
  "von grosser tragweite",
  "nachhaltig",
  "nachhaltigkeit",
  "resilient",
  "resilienz",
  "agil",
  "agilitaet",
  "skalierbar",
  "skalierbarkeit",
  "optimieren",
  "optimierung",
  "implementieren",
  "implementierung",
  "evaluieren",
  "evaluierung",
  "analysieren",
  "eruieren",
  "verifizieren",
  "validieren",
  "konkretisieren",
  "operationalisieren",
  "priorisieren",
  "fokussieren",
  "adressieren",
  "thematisieren",
  "initiieren",
  "forcieren",
  "intensivieren",
  "vorantreiben",
  "beschleunigen",
  "katalysieren",
  "proaktiv",
  "praezedenzlos",
  "state of the art",
  "best practice",
  "benchmark",
  "roadmap",
  "stakeholder",
  "framework",
  "mindset",
  "enabler",
  "gamechanger",
  "deep dive",
  "hands-on",
  "bottom-up",
  "top-down",
  "end-to-end",
  "win-win-situation",
  "pain point",
  "use case",
  "value proposition",
  "in der heutigen schnelllebigen welt",
  "in der heutigen digitalen welt",
  "im digitalen zeitalter",
  "im zeitalter der digitalisierung",
  "in einer zunehmend vernetzten welt",
  "in einer welt in der",
  "tauchen wir ein",
  "tauchen wir tiefer ein",
  "lass uns eintauchen",
  "lassen sie uns eintauchen",
  "eintauchen in",
  "werfen wir einen blick",
  "werfen wir einen genaueren blick",
  "hast du dich jemals gefragt",
  "haben sie sich jemals gefragt",
  "wichtig zu beachten",
  "wichtig zu betonen",
  "wichtig zu verstehen",
  "es ist entscheidend",
  "es ist unerlaesslich",
  "es sei angemerkt",
  "zusammenfassend laesst sich sagen",
  "abschliessend laesst sich sagen",
  "alles in allem",
  "kurz gesagt",
  "auf den punkt gebracht",
  "letztendlich",
  "im kern",
  "spannende reise",
  "auf eine reise",
  "eine reise durch",
  "ein zeugnis fuer",
  "zeugt von",
  "eindrucksvoll",
  "nuanciert",
  "im stetigen wandel",
  "sich staendig wandelnd",
  "sich rasant entwickelnd",
  "rasant entwickelnden",
  "eine entscheidende rolle",
  "eine schluesselrolle",
  "eine zentrale rolle",
  "ein echter gamechanger",
  "game changer",
  "game-changer",
  "auf das naechste level",
  "auf ein neues level",
  "das naechste level",
  "next level",
  "mehrwert schaffen",
  "mehrwert bieten",
  "echten mehrwert",
  "synergien nutzen",
  "synergien schaffen",
  "das volle potenzial",
  "volles potenzial",
  "potenzial ausschoepfen",
  "nahtlose integration",
  "nahtlos integrieren",
  "nahtlos integriert",
  "massgeschneiderte loesungen",
  "innovative loesungen",
  "ganzheitlicher ansatz",
  "zukunftssicher",
  "neue massstaebe",
  "revolutionieren",
  "revolutioniert",
  "ich hoffe das hilft",
  "ich hoffe dies hilft",
  "gute frage",
  "tolle frage",
  "ausgezeichnete frage",
  "gerne helfe ich",
  "ich helfe dir gerne",
  "ich helfe ihnen gerne",
  "lass es mich wissen",
  "lassen sie es mich wissen",
  "zoegere nicht",
  "zoegern sie nicht",
  "als ki-sprachmodell",
  "du hast absolut recht",
  "sie haben absolut recht",
  "ich entschuldige mich fuer die verwirrung"
 ],
 "patterns": [
  {
   "name": "em-dash-abuse",
   "pattern": "\\u2014[^\\u2014\\n]*\\u2014[^\\u2014\\n]*\\u2014[^\\n]*",
   "weight": 5,
   "description": "Excessive em-dash usage (3+ per paragraph) is a strong AI writing signal"
  },
  {
   "name": "let-me-starter",
   "pattern": "^\\s*let me \\w+",
   "flags": "im",
   "weight": 3,
   "description": "\"Let me [verb]\" sentence starters are characteristic of AI assistants"
  },
  {
   "name": "heres-the-thing",
   "pattern": "here'?s (the thing|what|the deal|the kicker)",
   "flags": "i",
   "weight": 3,
   "description": "\"Here's the thing/what\" openers mimic conversational AI tone"
  },
  {
   "name": "binary-contrast",
   "pattern": "not (just|only|merely|simply) .{2,40}?,? but (also )?",
   "flags": "i",
   "weight": 3,
   "description": "Binary contrast structures (\"Not just X, but Y\", \"not only X but also Y\") are over-used by AI"
  },
  {
   "name": "negation-pivot",
   "pattern": "\\b(?:it|this|that)(?:'s not| is not| was not| isn't| wasn't) (?:just |only |merely |simply |about )*[^.!?\\n]{2,60}?(?:[,;:\\u2014\\u2013]|\\.\\s+)\\s*(?:it|this|that)(?:'s| is| was)\\b",
   "flags": "gi",
   "weight": 3,
   "maxCount": 3,
   "description": "\"It's not X, it's Y\" pivots (\"This isn't a tool. It's a teammate.\") are a signature AI rhetorical move"
  },
  {
   "name": "binary-contrast-de",
   "pattern": "\\bnicht nur\\b[^.!?\\n]{2,60}?,?\\s+sondern auch\\b",
   "flags": "giu",
   "weight": 3,
   "description": "German binary contrast (\"nicht nur X, sondern auch Y\") is over-used by AI"
  },
  {
   "name": "wh-starters",
   "pattern": "^\\s*(what makes this|why this matters|why it matters|how this works|what this means|where this gets interesting)",
   "flags": "im",
   "weight": 4,
   "description": "Wh- question starters used as section headers are an AI pattern"
  },
  {
   "name": "bullet-overload",
   "pattern": "(^\\s*[-*]\\s.+\\n){6,}",
   "flags": "m",
   "weight": 4,
   "description": "Long bullet-point lists (6+) without prose are a structural AI pattern",
   "maxCount": 3
  },
  {
   "name": "triple-adjective",
   "pattern": "\\b\\w+(?:ly)?\\b,\\s+\\b\\w+(?:ly)?\\b,\\s+(?:and\\s+)?\\b\\w+(?:ly)?\\b\\s+\\w+",
   "flags": "i",
   "weight": 2,
   "description": "Triple adjective chains before nouns are more common in AI writing",
   "maxCount": 1
  },
  {
   "name": "meta-reference",
   "pattern": "in this (article|post|guide|blog|piece|section|tutorial|overview|essay)",
   "flags": "i",
   "weight": 3,
   "description": "Self-referencing meta text is common in AI-generated content"
  },
  {
   "name": "passive-voice-density",
   "pattern": "\\b(is|are|was|were|been|being)\\s+\\w+ed\\b",
   "flags": "gi",
   "weight": 1,
   "description": "Individual passive voice instance (aggregated for density check)"
  },
  {
   "name": "worth-noting",
   "pattern": "^\\s*it('s|\\s+is)\\s+worth\\s+(noting|mentioning|highlighting|pointing out)",
   "flags": "im",
   "weight": 4,
   "description": "\"It's worth noting\" as a sentence opener is a strong AI signal"
  },
  {
   "name": "colon-list-intro",
   "pattern": ":\\s*\\n\\s*[-*1]",
   "flags": "m",
   "weight": 2,
   "description": "Colon followed by a list is a common AI formatting pattern",
   "maxCount": 3
  },
  {
   "name": "emoji-header",
   "pattern": "^\\s*(?:#{1,6}\\s+\\p{Extended_Pictographic}|\\p{Extended_Pictographic}\\uFE0F?\\s+\\*\\*)",
   "flags": "mu",
   "weight": 5,
   "description": "Emoji used as header markers (\"🚀 **Speed**\", \"## ✅ Done\") are a strong AI formatting signal",
   "maxCount": 3
  },
  {
   "name": "number-list-pattern",
   "pattern": "^\\s*\\d+\\.\\s+\\*\\*.+\\*\\*",
   "flags": "m",
   "weight": 2,
   "description": "Numbered lists with bold items are commonly AI-generated",
   "maxCount": 3
  },
  {
   "name": "tldr-pattern",
   "pattern": "(tl;?dr|key takeaway|bottom line|in a nutshell)\\s*:?\\s*\\n",
   "flags": "im",
   "weight": 3,
   "description": "TL;DR / key takeaway sections are AI structural patterns"
  }
 ]
};
